# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  - DB=mysql

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS mwash_db;" -u root; fi
  - composer install

script:
  - cd application/tests
  - phpunit --coverage-text
